apiVersion: tekton.dev/v1beta1
kind: Task
spec:
  steps:
    - args:
        - '-c'
        - >-
          export HOME=/root && [ -f /root/.nvm/nvm.sh ] && chmod +x
          /root/.nvm/nvm.sh && source /root/.nvm/nvm.sh || true && cd /workspace
          && cp /var/scripts/run0 /tmp/run && chmod +x /tmp/run && /tmp/run
      command:
        - bash
      image: 'icr.io/continuous-delivery/pipeline/pipeline-base-image:latest'
      name: build0
      resources: {}
      volumeMounts:
        - mountPath: /var/scripts
          name: scripts
    - args:
        - '-c'
        - >-
          cd /workspace && cp /var/scripts/run1 /tmp/run && chmod +x /tmp/run &&
          /tmp/run
      command:
        - sh
      image: 'us.icr.io/dev-cedp-security/bifrost:2.0'
      imagePullPolicy: Always
      name: build1
      resources: {}
      volumeMounts:
        - mountPath: /var/scripts
          name: scripts
    - args:
        - '-c'
        - >-
          export HOME=/root && [ -f /root/.nvm/nvm.sh ] && chmod +x
          /root/.nvm/nvm.sh && source /root/.nvm/nvm.sh || true && cd /workspace
          && cp /var/scripts/run2 /tmp/run && chmod +x /tmp/run && /tmp/run
      command:
        - bash
      image: 'icr.io/continuous-delivery/pipeline/pipeline-base-image:latest'
      name: build2
      resources: {}
      volumeMounts:
        - mountPath: /var/scripts
          name: scripts
  sidecars:
    - securityContext:
        privileged: true
  volumes:
    - configMap:
        name: scripts
      name: scripts
