---
stages:
- name: Versions
  inputs:
  - service: ${GIT_REPO}
    type: git
    branch: '{{form.pipeline.parameters.prod-INPUT_GIT_BRANCH}}'
    dir_name: null
  triggers:
  - type: git
    events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Pull'
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
    build_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      
      ibm-bifrost versions --pull ${STG_VERSIONS_GIT_BRANCH}
      mv .git git
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: Plan
  inputs:
  - type: job
    stage: Versions
    job: 'Pull'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Build'
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
    build_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      mv git .git
      ibm-bifrost plan -d "${DESTINATION}" full
      mv .git git
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: Deploy
  inputs:
  - type: job
    stage: Plan
    job: 'Build'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: ${DESTINATION}
    type: deployer
    curatedDockerImage: default
    deploy_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      export REGION=$(echo $REGISTRY_REGION_ID | cut -f3 -d:)
      export TOOLCHAIN_ID=$PIPELINE_TOOLCHAIN_ID
      export IBMCLOUD_HOME=${IBMCLOUD_HOME}
      export ORGANIZATION=https://cloud.ibm.com
      ibm-bifrost login --public-cloud
      ibmcloud cs init
      ibmcloud cs clusters
      ibmcloud ks cluster config --cluster ${CLUSTER}
      ibm-bifrost deploy --run
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
  - name: 'Validate'
    type: deployer
    curatedDockerImage: default
    deploy_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      export REGION=$(echo $REGISTRY_REGION_ID | cut -f3 -d:)
      export TOOLCHAIN_ID=$PIPELINE_TOOLCHAIN_ID
      export IBMCLOUD_HOME=${IBMCLOUD_HOME}
      export ORGANIZATION=https://cloud.ibm.com
      ibm-bifrost login --public-cloud
      ibmcloud cs init
      ibmcloud cs clusters
      ibmcloud ks cluster config --cluster ${CLUSTER}
      ibm-bifrost deploy --validate
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: Versions
  inputs:
  - type: job
    stage: Plan
    job: 'Build'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Push'
    type: deployer
    curatedDockerImage: default
    deploy_type: customimage
    script: |-
      #!/bin/bash
      set -x
      set -e
      pwd
      mv git .git
      git config --global user.email "toolchain@cloud.ibm.com"
      git config --global user.name "IBM Cloud DevOps Toochain"
      ibm-bifrost versions --push ${VERSIONS_GIT_BRANCH}
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
hooks:
- enabled: true
  label: null
  ssl_enabled: true
  url: https://devops-api.us-south.devops.cloud.ibm.com/v1/messaging/webhook/publish
defaultBaseImageVersion: latest
properties:
- name: DESTINATION
  value: '{{form.pipeline.parameters.prod-destination}}'
  type: text
- name: DOCKER_IMAGE_NAME
  value: '{{form.pipeline.parameters.dockerImageName}}'
  type: text
- name: IBM_CLOUD_API_KEY
  value: '{{form.pipeline.parameters.api-key}}'
  type: secure
- name: DOCKER_USERNAME
  value: 'iamapikey'
  type: text
- name: DOCKER_PASSWORD
  value: '{{form.pipeline.parameters.api-key}}'
  type: secure 
- name: REGISTRY_REGION_ID
  value: '{{form.pipeline.parameters.registry-region}}'
  type: text
- name: CLUSTER
  value: '{{form.pipeline.parameters.prod-cluster}}'
  type: text
- name: DOMAIN
  value: '{{form.pipeline.parameters.prod-domain}}'
  type: text
- name: EXTERNAL_IP
  value: '{{form.pipeline.parameters.prod-externalIP}}'
  type: text
- name: INPUT_GIT_BRANCH 
  value: '{{form.pipeline.parameters.prod-INPUT_GIT_BRANCH}}'
  type: text
- name: GIT_REPO 
  value: 'https://github.ibm.com/CEDP-Garage/cedp-garage-pipelines.git'
  type: text
- name: VERSIONS_GIT_BRANCH 
  value: '{{form.pipeline.parameters.prod-VERSIONS_GIT_BRANCH}}'
  type: text
- name: STG_VERSIONS_GIT_BRANCH 
  value: '{{form.pipeline.parameters.stg-VERSIONS_GIT_BRANCH}}'
  type: text
- name: VERDACCIO_USER 
  value: '{{form.pipeline.parameters.VERDACCIO_USER}}'
  type: text
- name: VERDACCIO_EMAIL
  value: '{{form.pipeline.parameters.VERDACCIO_EMAIL}}'
  type: text
- name: VERDACCIO_PASSWORD 
  value: '{{form.pipeline.parameters.VERDACCIO_PASSWORD}}'
  type: secure
- name: ARTIFACTORY_USER
  value: '{{form.pipeline.parameters.ARTIFACTORY_USER}}'
  type: text
- name: ARTIFACTORY_APIKEY 
  value: '{{form.pipeline.parameters.ARTIFACTORY_APIKEY}}'
  type: secure
- name: ARTIFACTORY_URL 
  value: '{{form.pipeline.parameters.ARTIFACTORY_URL}}'
  type: text
- name: ICP_USER 
  value: '{{form.pipeline.parameters.ICP_USER}}'
  type: text
- name: ICP_PASSWORD 
  value: '{{form.pipeline.parameters.ICP_PASSWORD}}'
  type: secure
- name: NAMESPACE 
  value: '{{form.pipeline.parameters.dev-namespace}}'
  type: text
- name: IBMCLOUD_HOME 
  value: '/root'
  type: text
