---
stages:
- name: Versions
  inputs:
  - service: ${GIT_REPO}
    type: git
    branch: '{{form.pipeline.parameters.prod-INPUT_GIT_BRANCH}}'
    dir_name: null
  triggers:
  - type: git
    events: '{"push":false,"pull_request":true,"pull_request_closed":false}'
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Pull'
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
    build_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      env
      ibm-bifrost versions pull "$VERSIONS_GIT_BRANCH"
      mv .git git
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: Plan
  inputs:
  - type: job
    stage: Versions
    job: 'Pull'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Build'
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
    build_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      env
      mv git .git
      ibm-bifrost build_plan "${DESTINATION}" diff pr
      mv .git git
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: Unit tests
  inputs:
  - type: job
    stage: Plan
    job: 'Build'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Test'
    type: builder
    curatedDockerImage: default
    artifact_dir: ''
    build_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      export REGION=$(echo $REGISTRY_REGION_ID | cut -f3 -d:)
      export TOOLCHAIN_ID=$PIPELINE_TOOLCHAIN_ID
      export HOME=${IBMCLOUD_HOME}
      ibmcloud login -a cloud.ibm.com -r "${REGION}" --apikey ${IBM_CLOUD_API_KEY}
      export MAVEN_OPTS="-Xmx1000m"
      ibm-bifrost build_code test-only
      
    namespace: 'NULL'
    docker_image: ${DOCKER_IMAGE_NAME}
- name: 'Sonar Qube'
  inputs:
  - type: job
    stage: Unit tests
    job: 'Test'
    dir_name: null
  triggers:
  - type: stage
  permission:
    execute: TOOLCHAIN_ADMINS
  jobs:
  - name: 'Validate'
    type: tester
    curatedDockerImage: default
    test_type: customimage
    script: |-
      #********************************************
      #!/bin/bash
      set -x
      set -e
      export REGION=$(echo $REGISTRY_REGION_ID | cut -f3 -d:)
      export TOOLCHAIN_ID=$PIPELINE_TOOLCHAIN_ID
      ibmcloud login -a cloud.ibm.com -r "${REGION}" --apikey ${IBM_CLOUD_API_KEY}
      sonar-scanner --version
      ibm-bifrost sonar_validate

    namespace: 'NULL'      
    docker_image: ${DOCKER_IMAGE_NAME}
hooks:
- enabled: true
  label: null
  ssl_enabled: true
  url: https://devops-api.us-south.devops.cloud.ibm.com/v1/messaging/webhook/publish
defaultBaseImageVersion: latest
properties:
- name: DESTINATION
  value: '{{form.pipeline.parameters.prod-destination}}'
  type: text
- name: DOCKER_IMAGE_NAME
  value: '{{form.pipeline.parameters.dockerImageName}}'
  type: text
- name: IBM_CLOUD_API_KEY
  value: '{{form.pipeline.parameters.api-key}}'
  type: secure
- name: DOCKER_USERNAME
  value: 'iamapikey'
  type: text
- name: DOCKER_PASSWORD
  value: '{{form.pipeline.parameters.api-key}}'
  type: secure 
- name: CREDENTIALS
  value: '{{form.pipeline.parameters.prod-CREDENTIALS}}'
  type: secure
- name: REGISTRY_REGION_ID
  value: '{{form.pipeline.parameters.registry-region}}'
  type: text
- name: INPUT_GIT_BRANCH 
  value: '{{form.pipeline.parameters.prod-INPUT_GIT_BRANCH}}'
  type: text
- name: GIT_REPO 
  value: 'https://github.ibm.com/CEDP-Garage/cedp-garage-pipelines.git'
  type: text
- name: VERSIONS_GIT_BRANCH 
  value: '{{form.pipeline.parameters.prod-VERSIONS_GIT_BRANCH}}'
  type: text
- name: ARTIFACTORY_USER 
  value: '{{form.pipeline.parameters.ARTIFACTORY_USER}}'
  type: text
- name: ARTIFACTORY_APIKEY 
  value: '{{form.pipeline.parameters.ARTIFACTORY_APIKEY}}'
  type: secure
- name: DOMAIN
  value: '{{form.pipeline.parameters.prod-domain}}'
  type: text
- name: IBMCLOUD_HOME 
  value: '/root'
  type: text